# Generated by Django 2.1.5 on 2019-05-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='0@gmail.com', max_length=254, null=True, unique=True, verbose_name='Name User'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default='nothing', max_length=120, null=True, verbose_name='Real Email'),
        ),
    ]
