# Generated by Django 2.1.5 on 2019-07-02 21:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lex_pusher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('solo_mmr', models.CharField(max_length=120)),
                ('party_mmr', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=lex_pusher.models.image_folder)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Буст',
                'verbose_name_plural': 'Аккаунты на продажу',
            },
        ),
        migrations.CreateModel(
            name='Bust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmr_from', models.IntegerField()),
                ('mmr_to', models.IntegerField()),
                ('mmr_current', models.IntegerField()),
                ('steam_login', models.CharField(max_length=120)),
                ('steam_password', models.CharField(max_length=120)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Буст',
                'verbose_name_plural': 'Бусты',
            },
        ),
        migrations.CreateModel(
            name='Buster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(blank=True, default='ссс/ccc.png', null=True, upload_to='')),
                ('vk', models.CharField(blank=True, max_length=120, null=True)),
                ('skype', models.CharField(blank=True, max_length=120, null=True)),
                ('wmr', models.CharField(blank=True, max_length=120, null=True)),
                ('solo_mmr', models.IntegerField(default=1)),
                ('experience', models.TextField(default='Nothing')),
                ('booster_acc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на бустера',
                'verbose_name_plural': 'Заявки на бустера',
            },
        ),
        migrations.CreateModel(
            name='BuyAccount',
            fields=[
                ('account_slug', models.SlugField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=120)),
                ('skype', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Покупатели аккаунтов готовых',
            },
        ),
        migrations.CreateModel(
            name='Punish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0)),
                ('reason', models.TextField(default='Бан по причине')),
                ('buster_ident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lex_pusher.Buster')),
            ],
            options={
                'verbose_name': 'Штраф',
                'verbose_name_plural': 'Штрафы',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=255)),
                ('mmr', models.FloatField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('bust', models.ForeignKey(on_delete=True, to='lex_pusher.Bust')),
            ],
            options={
                'verbose_name': 'Стат',
                'verbose_name_plural': 'Статы',
            },
        ),
        migrations.AddField(
            model_name='bust',
            name='buster_id',
            field=models.ForeignKey(null=True, on_delete=True, to='lex_pusher.Buster'),
        ),
        migrations.AddField(
            model_name='bust',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
