# Generated by Django 2.2.4 on 2019-08-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='party_mmr',
            new_name='core_mmr',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='solo_mmr',
            new_name='support_mmr',
        ),
    ]
