# Generated by Django 2.1.5 on 2019-06-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bust',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
