# Generated by Django 2.1.5 on 2019-05-11 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bust',
            old_name='user',
            new_name='client_id',
        ),
    ]
