# Generated by Django 2.1.5 on 2019-05-11 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0002_auto_20190512_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bust',
            old_name='client_id',
            new_name='client',
        ),
    ]
