# Generated by Django 2.1.5 on 2019-05-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0002_buyaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyaccount',
            name='account',
        ),
        migrations.AddField(
            model_name='buyaccount',
            name='account_slug',
            field=models.SlugField(default='acc 322'),
        ),
    ]
