# Generated by Django 2.2.4 on 2019-08-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0002_auto_20190811_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='price',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
