# Generated by Django 2.1.5 on 2019-06-14 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0002_bust_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0)),
                ('reason', models.TextField(default='Бан по причине')),
            ],
        ),
        migrations.AddField(
            model_name='buster',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='punish',
            name='buster_ident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lex_pusher.Buster'),
        ),
    ]
