# Generated by Django 2.1.5 on 2019-06-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0003_auto_20190614_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punish',
            options={'verbose_name': 'Штраф', 'verbose_name_plural': 'Штрафы'},
        ),
        migrations.RemoveField(
            model_name='bust',
            name='is_active',
        ),
        migrations.AddField(
            model_name='bust',
            name='mmr_current',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
