# Generated by Django 2.2.4 on 2019-08-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0003_auto_20190813_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=120)),
                ('steam_password', models.CharField(max_length=120)),
                ('steam_login', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField(default=0)),
                ('mmr', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Калибровка',
                'verbose_name_plural': 'Калибровки',
            },
        ),
    ]
