# Generated by Django 2.1.5 on 2019-06-27 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0004_auto_20190626_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='screen',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
