# Generated by Django 2.1.5 on 2019-05-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0005_boost_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boost',
            new_name='Client',
        ),
        migrations.AddField(
            model_name='buyaccount',
            name='party_mmr',
            field=models.CharField(default=2000, max_length=120),
        ),
        migrations.AddField(
            model_name='buyaccount',
            name='solo_mmr',
            field=models.CharField(default=1, max_length=120),
        ),
    ]
