# Generated by Django 2.1.5 on 2019-06-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0005_auto_20190627_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='match_id',
        ),
    ]
