# Generated by Django 2.2.4 on 2019-08-20 11:19

from django.db import migrations, models
import lex_pusher.models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0005_bust_mmr_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='image',
            new_name='image_avatar',
        ),
        migrations.AddField(
            model_name='account',
            name='image_main',
            field=models.ImageField(default=1, upload_to=lex_pusher.models.image_folder),
            preserve_default=False,
        ),
    ]
