# Generated by Django 2.1.5 on 2019-06-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0006_remove_stat_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buster',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
