# Generated by Django 2.1.5 on 2019-05-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0006_auto_20190504_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyaccount',
            name='party_mmr',
        ),
        migrations.RemoveField(
            model_name='buyaccount',
            name='solo_mmr',
        ),
    ]
