# Generated by Django 2.2.4 on 2019-08-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0006_auto_20190820_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dotabuff',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='steam_acc',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
