# Generated by Django 2.1.5 on 2019-05-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0007_auto_20190504_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='PHONE', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='skype',
            field=models.CharField(blank=True, default='Skype', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='vk',
            field=models.CharField(blank=True, default='VK', max_length=120, null=True),
        ),
    ]
