# Generated by Django 2.1.5 on 2019-06-27 18:09

from django.db import migrations, models
import lex_pusher.models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0007_buster_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buster',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=lex_pusher.models.image_folder),
        ),
    ]
