# Generated by Django 2.1.5 on 2019-06-27 21:37

from django.db import migrations, models
import lex_pusher.models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0008_auto_20190627_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buster',
            name='avatar',
            field=models.ImageField(blank=True, default='media/ccc.png', null=True, upload_to=lex_pusher.models.image_buster_folder),
        ),
    ]
