# Generated by Django 2.1.5 on 2019-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0008_auto_20190504_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='cebek', null=True)),
                ('mmr_from', models.IntegerField()),
                ('mmr_to', models.IntegerField()),
                ('steam_login', models.CharField(max_length=120)),
                ('steam_password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Buster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='cebek')),
                ('password', models.CharField(max_length=120)),
                ('email', models.EmailField(default='0@gmail.com', max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='login',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mmr_from',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mmr_to',
        ),
        migrations.RemoveField(
            model_name='client',
            name='more_info',
        ),
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, default='model'),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(default='password', max_length=120),
        ),
        migrations.AddField(
            model_name='bust',
            name='buster_slug',
            field=models.ForeignKey(null=True, on_delete=True, to='lex_pusher.Buster'),
        ),
        migrations.AddField(
            model_name='bust',
            name='client_slug',
            field=models.ForeignKey(null=True, on_delete=True, to='lex_pusher.Client'),
        ),
    ]
