# Generated by Django 2.2.4 on 2019-08-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0008_auto_20190822_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='steam_login',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='steam_password',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
