# Generated by Django 2.1.5 on 2019-05-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0009_auto_20190506_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bust',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buster',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
