# Generated by Django 2.1.5 on 2019-06-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0009_auto_20190627_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buster',
            name='avatar',
            field=models.ImageField(blank=True, default='media/ссс/ccc.png', null=True, upload_to='media/avatars'),
        ),
    ]
