# Generated by Django 2.2.4 on 2019-08-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0010_auto_20190824_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='buster',
            field=models.ForeignKey(default=True, on_delete=True, to='lex_pusher.Buster'),
            preserve_default=False,
        ),
    ]
