# Generated by Django 2.1.5 on 2019-05-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0010_auto_20190507_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mmr', models.FloatField()),
                ('is_win', models.BooleanField()),
                ('time', models.TimeField()),
                ('bust_id', models.ForeignKey(on_delete=True, to='lex_pusher.Bust')),
            ],
        ),
    ]
