# Generated by Django 2.2.4 on 2019-08-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0011_stat_buster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты на продажу'},
        ),
        migrations.AddField(
            model_name='calibration',
            name='buster',
            field=models.ForeignKey(null=True, on_delete=True, to='lex_pusher.Buster'),
        ),
    ]
