# Generated by Django 2.1.5 on 2019-05-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0011_stats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
    ]
