# Generated by Django 2.2 on 2019-07-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0011_auto_20190701_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='bust_id',
            new_name='bust',
        ),
    ]
