# Generated by Django 2.2.4 on 2019-08-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0012_auto_20190827_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
