# Generated by Django 2.2 on 2019-05-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0012_auto_20190508_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bust',
            name='buster_slug',
        ),
        migrations.RemoveField(
            model_name='bust',
            name='client_slug',
        ),
        migrations.RemoveField(
            model_name='bust',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='buster',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='client',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='is_win',
        ),
        migrations.AddField(
            model_name='bust',
            name='buster_id',
            field=models.ForeignKey(null=True, on_delete=True, to='lex_pusher.Buster'),
        ),
        migrations.AddField(
            model_name='bust',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=True, to='lex_pusher.Client'),
        ),
        migrations.AddField(
            model_name='bust',
            name='steam_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stat',
            name='match_id',
            field=models.IntegerField(),
        ),
    ]
