# Generated by Django 2.2.4 on 2019-08-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0013_calibration_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bust',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Calibration',
        ),
    ]
