# Generated by Django 2.2 on 2019-05-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0014_auto_20190510_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
