# Generated by Django 2.2 on 2019-05-10 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0015_auto_20190510_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='bust',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
