# Generated by Django 2.2.4 on 2019-08-29 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0015_auto_20190829_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='bust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lex_pusher.Bust'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='buster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lex_pusher.Buster'),
        ),
    ]
