# Generated by Django 2.2 on 2019-05-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0016_bust_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bust',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
