# Generated by Django 2.2.4 on 2019-08-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0016_auto_20190829_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buster',
            old_name='wmr',
            new_name='card',
        ),
        migrations.AddField(
            model_name='buster',
            name='qiwi',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
