# Generated by Django 2.2 on 2019-05-10 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_pusher', '0017_auto_20190510_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bust',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
